### ISSUE TITLE
 google drive

### ISSUE THREAD

**Issue by mrqaidi** [madcode-git/YouTube-Downloader#1]
Hi

is it possible to use this on  google drive mp4 file  ?

**Comment by hex-firebone** [comment]
@mrqaidi This is a YouTube Video Downloader.

But I will make something for you,maybe another project

**Comment by madcode-git** [comment]
@mrqaidi, sorry bro!!!

My pc's power supply is dead.

Please provide me your mail and I will try to provide you a private library.
