### ISSUE TITLE
Audio only

### ISSUE THREAD

**Issue by chadul** [madcode-git/YouTube-Downloader#2]
How to get audio only or video only?

**Comment by madcode-git** [comment]
Currently it only provides the video(including audio) file's links.

I add other formats on next update.

Thanks for your enlightenment.

**Comment by madcode-git** [comment]
Hey @chadul ,

Now Audio and Video both are added here.

Please check and confirm.

Thanks.

**Comment by madcode-git** [comment]
@chadul 

With the update of __[Version 2.0](https://github.com/madcode-git/YouTube-Downloader/releases/tag/2.0)__, I'm closing this issue.
