### ISSUE TITLE
Downloader not working

### ISSUE THREAD

**Issue by harisnaeemofficial** [madcode-git/YouTube-Downloader#3]
There is a another method to get youtube download links with signature youtube-dl also stops working before the 8-9-2018 update . Please have a look on code and tell me if solve the error

**Comment by madcode-git** [comment]
I will try to fix it.Thanks for letting me know about it.

**Comment by madcode-git** [comment]
Please now have a look

**Comment by FaArIsH** [comment]
thanks but only 360p and lower working .
720P and higher don't work

**Comment by madcode-git** [comment]
720p works only on that ip from which the the request was sent.

**Comment by madcode-git** [comment]
Hi,

It seems that all videos which are copyrighted, don't have 720p video anymore.

Youtube is trying to protect contents theft by limiting the available video quality.

As for streaming HD videos in Youtube.com , They are streaming Dash video and Dash audio file both together at the same time.

**Comment by madcode-git** [comment]
Please provide link to those videos.

**Comment by FaArIsH** [comment]
@harisnaeemofficial as he said "720p works only on that ip from which the the request was sent" your above videos work with the IP the request was sent from.

**Comment by harisnaeemofficial** [comment]
I am not talking about 720p . These videos are not downloading in any format .

**Comment by FaArIsH** [comment]
@harisnaeemofficial yes I tried the 360p link from my phone and it shows error page but I tried the link using the server proxy and it works

**Comment by harisnaeemofficial** [comment]
@FaArIsH which video link you tried? send me downloadable URL and your downloader.php file i will try

**Comment by harisnaeemofficial** [comment]
Yes its working fine in my localhost Thanks for your response .
 I am using downloader file in my website don't know why it is not working for some videos

**Comment by madcode-git** [comment]
I will study on your problem and will try to fix it by this week.

**Comment by madcode-git** [comment]
@FaArIsH Actually, 720p format video is removed from youtube for copyrighted videos.

**Comment by madcode-git** [comment]
Hi,
Now I have added built-in german proxy.

Hoping that no would have to face 403 error anymore.

You should update your composer package by this command

```
composer require madcodez/youtube-downloader:dev-proxied
```

The Source is on [proxied branch](https://github.com/madcode-git/YouTube-Downloader/tree/proxied)

Give an update on this guys...

**Comment by harisnaeemofficial** [comment]
Can we replace http://ss.de.prx.genyoutube.com Url with our website url ?
or hide this **http://ss.de.prx.genyoutube.com**/redirector.googlevideo.com/videoplayback?signature=7F9C3146F2A7349255BDAFB15441DBFEE7542B16.B4CACED1225241404C049DA5CAA63451244FD057&requiressl=yes&itag=22&gcr=de&ei=epLYW97aJ4S-hAfM-KugBg&expire=1540941530&dur=311.379&source=youtube&initcwndbps=1416250&key=yt6&lmt=1540482332001167&ratebypass=yes&c=WEB&txp=5531432&ipbits=0&mm=31%2C26&ip=195.201.23.127&mn=sn-4g5e6nls%2Csn-5hne6n7z&mime=video%2Fmp4&id=o-AGCF7v28dRnjthc12IcqAkmSKdPZ6I7X-nOtMLY3o5NC&pl=23&sparams=dur%2Cei%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mt=1540919807&mv=m&ms=au%2Conr&fvip=4&title=Chote-Bache-Ka-Ghussa-Karne-Ka-Munfarid-Andaz

in this URL.

**Comment by madcode-git** [comment]
@harisnaeemofficial

http://ss.de.prx.genyoutube.com


Is the proxy brother...


If your have a vps server than you can also setup like genyoutube's proxy.

**Comment by harisnaeemofficial** [comment]
@madcode-git Yes i know but i dont know how to create my own proxy on my hosting with this downloader can you suggest me or tell me how can i create my own proxy with this downloader . My web site is www.vinepk.com

**Comment by madcode-git** [comment]
You would first need a vps server with unmetered brandwidth.

**Comment by madcode-git** [comment]
Nice design you got there... Hey let's no flood this place. Come into my inbox if you need any personal help.

Ok....

**Comment by madcode-git** [comment]
Hi @harisnaeemofficial ,

All the problems are fixed with the new release of version 0.1.6

Please try and give me feedback.

Thanks
