### ISSUE TITLE
403. That’s an error.  Your client does not have permission to get URL /videoplayback?........

### ISSUE THREAD

**Issue by zxq2233** [madcode-git/YouTube-Downloader#4]
![baidushurufa_2018-9-29_7-1-4](https://user-images.githubusercontent.com/14195738/46322616-7ccd1880-c61c-11e8-890b-e0d599433df6.png)
![baidushurufa_2018-10-2_8-23-35](https://user-images.githubusercontent.com/14195738/46322617-7d65af00-c61c-11e8-8b18-f8a140115052.png)

**Comment by madcode-git** [comment]
Please check now...

**Comment by FaArIsH** [comment]
@madcode-git q quote from a dev
> 
> 
> .yo, just wanted to say thanks for your efforts with that like.
> Im not looking for hd content with my fork, so i just changed the regexp to cope with youtubes sep18 changes.
> But- for the current threads question - you might want to parse
> 'https://www.youtube.com/get_video_info?
> and look for the [adaptive_fmts] array.
> 
> enjoy, arjunae

**Comment by madcode-git** [comment]
Yes, the code came from @arjunae

Thanks to @arjunae

**Comment by madcode-git** [comment]
@zxq2233 and @FaArIsH   The Regex has been updated with Youtube-dl's official Regex.

Also, it seems that all videos which are copyrighted, don't have 720p video anymore.

Youtube is trying to protect contents theft by limiting the available video quality.

As for streaming HD videos in Youtube.com , They are streaming Dash video and Dash audio file both together at the same time.

**Comment by madcode-git** [comment]
Clone of #3 

So, closing this down. Check here #3 for more update
