### ISSUE TITLE
Invalid argument supplied for foreach() YTDownloader.php on line 251

### ISSUE THREAD

**Issue by aloneblessyou** [madcode-git/YouTube-Downloader#5]
hi, please help me

**Comment by madcode-git** [comment]
Are getting this error in localhost??

Then it might be a issue with your network... Can you please confirm, on which platform are you on??

**Comment by madcode-git** [comment]
curl installed?? 

can you please come into inbox at madcode.git@gmail.com

**Comment by madcode-git** [comment]
Please check now

**Comment by madcode-git** [comment]
Hi @aloneblessyou ,

All the issues should be fixed with the new release of **version 0.1.6**

Please try and give me feedback.

Thanks
