### ISSUE TITLE
403 error in proxy branch

### ISSUE THREAD

**Issue by harisnaeemofficial** [madcode-git/YouTube-Downloader#7]
getting 403 error in proxy branch video id ffxKSjUwKdU
and many TSeries channel videos any solution ?

**Comment by harisnaeemofficial** [comment]
How do i get only 'dl' links from new updated file in master branch ? 
like $links['dl']['url'] ;  getting blank page from this method.

**Comment by madcode-git** [comment]
Proxy Branch has been dumped. Use master one. 

Please use the latest version of the library .

**Comment by harisnaeemofficial** [comment]
i am using latest version of master branch how do i get only dowload links from array?

**Comment by madcode-git** [comment]
```
$links['dl']
```

**Comment by harisnaeemofficial** [comment]
Not working this method return blank page

**Comment by madcode-git** [comment]
join in skype. Skype id : **madcode.git**
